<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LXG-PC" name="127.0.0.1:62025" tests="4" failures="2" timestamp="25 Dec 2016 05:57:02 GMT" time="191.001" errors="0">
  <testcase name="t001_login" time="28.345" classname="cn.crazy.appium.testcases.ZhiHuTest"/>
  <testcase name="t002_attention" time="34.168" classname="cn.crazy.appium.testcases.ZhiHuTest">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at cn.crazy.appium.testng.Assertion.fail(Assertion.java:66)
	at cn.crazy.appium.testng.Assertion.assertEquals(Assertion.java:20)
	at cn.crazy.appium.testcases.ZhiHuTest.t002_attention(ZhiHuTest.java:85)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- t002_attention -->
  <testcase name="t002_search" time="14.073" classname="cn.crazy.appium.testcases.ZhiHuTest"/>
  <testcase name="t004_personInfo" time="54.241" classname="cn.crazy.appium.testcases.ZhiHuTest">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at cn.crazy.appium.testng.Assertion.fail(Assertion.java:66)
	at cn.crazy.appium.testng.Assertion.assertEquals(Assertion.java:20)
	at cn.crazy.appium.testcases.ZhiHuTest.t004_personInfo(ZhiHuTest.java:103)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- t004_personInfo -->
</testsuite> <!-- 127.0.0.1:62025 -->
