<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="da926816"
           tests="2"
           failures="1"
           errors="0"
           skipped="1"
           time="0.000">
  <properties />
            <testcase name="afterClass" time="0.000" classname="cn.crazy.appium.testcases.ZhiHuTest">
                <failure type="java.lang.NullPointerException"
                  message="(null)"
              >
<![CDATA[java.lang.NullPointerException
  cn.crazy.appium.testcases.ZhiHuTest.afterClass(ZhiHuTest.java:147)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
  org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
  org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
  org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:232)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:115)
  org.testng.TestRunner.privateRun(TestRunner.java:782)
  org.testng.TestRunner.run(TestRunner.java:632)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
  org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
  org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
  org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
  
            <testcase name="t001_login" time="0.0" classname="cn.crazy.appium.testcases.ZhiHuTest">
          <skipped />
    </testcase>
  
  
</testsuite>
