<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="192.168.56.101:5555"
           tests="3"
           failures="2"
           errors="0"
           skipped="1"
           time="41.596">
  <properties />
            <testcase name="login" time="21.435" classname="cn.crazy.appium.network.study.Study2">
                <failure type="java.io.FileNotFoundException"
                  message="C:\Users\lixionggang\Desktop\test.xlsx (另一个程序正在使用此文件，进程无法访问。)"
              >
<![CDATA[java.io.FileNotFoundException: C:\Users\lixionggang\Desktop\test.xlsx (另一个程序正在使用此文件，进程无法访问。)
  java.io.FileOutputStream.open(Native Method)
  java.io.FileOutputStream.<init>(FileOutputStream.java:213)
  java.io.FileOutputStream.<init>(FileOutputStream.java:101)
  cn.crazy.appium.datadriver.ExcelUtil.setCellData(ExcelUtil.java:103)
  cn.crazy.appium.network.study.Study2.login(Study2.java:107)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:483)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
  org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
  org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
  java.util.concurrent.FutureTask.run(FutureTask.java:266)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  java.lang.Thread.run(Thread.java:745)
]]>
      </failure>

          </testcase>
            <testcase name="login" time="20.161" classname="cn.crazy.appium.network.study.Study2">
                <failure type="java.io.FileNotFoundException"
                  message="C:\Users\lixionggang\Desktop\test.xlsx (另一个程序正在使用此文件，进程无法访问。)"
              >
<![CDATA[java.io.FileNotFoundException: C:\Users\lixionggang\Desktop\test.xlsx (另一个程序正在使用此文件，进程无法访问。)
  java.io.FileOutputStream.open(Native Method)
  java.io.FileOutputStream.<init>(FileOutputStream.java:213)
  java.io.FileOutputStream.<init>(FileOutputStream.java:101)
  cn.crazy.appium.datadriver.ExcelUtil.setCellData(ExcelUtil.java:103)
  cn.crazy.appium.network.study.Study2.login(Study2.java:110)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:483)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
  org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
  org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
  java.util.concurrent.FutureTask.run(FutureTask.java:266)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  java.lang.Thread.run(Thread.java:745)
]]>
      </failure>

          </testcase>
  
            <testcase name="addAnswer" time="0.0" classname="cn.crazy.appium.network.study.Study2">
          <skipped />
    </testcase>
  
  
</testsuite>
