<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="dmall-zhang-PC" name="cn.crazy.appium.testcases.ZhiHuTest" tests="1" failures="0" timestamp="27 Dec 2016 07:36:32 GMT" time="0.000" errors="1">
  <testcase name="t001_login" time="0.000" classname="cn.crazy.appium.testcases.ZhiHuTest">
    <error type="java.lang.RuntimeException" message="java.io.FileNotFoundException: C:\Users\LXG\Desktop\test.xlsx (系统找不到指定的路径。)">
      <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: C:\Users\LXG\Desktop\test.xlsx (系统找不到指定的路径。)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:163)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: C:\Users\LXG\Desktop\test.xlsx (系统找不到指定的路径。)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(Unknown Source)
	at cn.crazy.appium.datadriver.ExcelUtil.getTestData(ExcelUtil.java:134)
	at cn.crazy.appium.testcases.ZhiHuTest.loginData(ZhiHuTest.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:137)
	... 16 more
]]>
    </error>
  </testcase> <!-- t001_login -->
</testsuite> <!-- cn.crazy.appium.testcases.ZhiHuTest -->
